function [BW,maskedImage] = segmentImage(X)
%segmentImage Segment image using auto-generated code from imageSegmenter App
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter App. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 02-Jan-2018
%----------------------------------------------------


% Convert from RGB to grayscale.
X = rgb2gray(X);

% Create empty mask.
BW = false(size(X));

% Polygon drawing
xPos = [1406.6695 1425.7870 1455.4004 1410.4180];
yPos = [1319.8909 1387.5519 1338.0713 1311.6441];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;